### ISSUE TITLE
Document examples of laypersons HPO autocomplete biolink API

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/phenotypr#2]
Add examples here...

**Comment by julesjacobsen** [comment]
From kent's email:

> I've written a wrapper over the solr endpoint I demoed last week.  The API function is available here:
>
>http://owlsim.monarchinitiative.org/api/#!/search/get_search_hpo_entities
>
>This is a temporary endpoint and will eventually be available on https://api.monarchinitiative.org/api/.  >Right now the response is very minimal, but we could add anything that is available from solr, and >theoretically anything from the ontology (I would need to index it first).  It likely needs improvement so >please let me know your feedback!
>

**Comment by julesjacobsen** [comment]
From Kent on using the Solr core:

>I want update everyone of my progress with our autocomplete service on the HPO plain language >terms.  I've written some code to pull out these terms and their phenotype and anatomy grouping >classes and index them in solr.  The code for this is here:
>
>https://github.com/monarch-initiative/hpo-plain-index
>
>The next step is writing a service that wraps solr and provides a cleaner interface for the client side code.  >I am hoping to have this done by early next week.
>
>The solr service is public if anyone would like to test it out.  Here are some sample queries:
>
>autocomplete: "frequent inf"
>expected: "frequent infections"
>facet:  Abnormality of the immune system
>hit: 1st
>
>Query: solr example 1
>
>autocomplete: "muscle ach"
>expected: "muscle ache"
>facet: Abnormality of the musculature
>hit: not found
>
>Query: solr example 2
>
>Not found see: https://github.com/obophenotype/human-phenotype-ontology/issues/3419
>
>autocomplete: "extra f"
>expected: "extra finger"
>facet: Abnormality of the hand
>hit: 2nd
>
>Query: solr example 3
>
>autocomplete: "extra fin"
>expected: "extra finger"
>facet: Abnormality of the hand
>hit: 1
>
>Query: solr example 4
>
>Solr endpoint:  https://solr.monarchinitiative.org/solr/hpo-pl/select/?q=*:*&wt=json&rows=200
>
>Best,
>Kent

**Comment by julesjacobsen** [comment]
@kshefchek that all still correct?

**Comment by kshefchek** [comment]
@julesjacobsen thanks! yes this is still correct.  I'll add a js mockup by tomorrow morning, but it is basically a wrapper over an ajax call.  For example:
https://gist.github.com/tkh44/11235101
https://github.com/putmantime/vue_autocomplete

**Comment by kshefchek** [comment]
example js widget: https://codepen.io/anon/pen/EExXaX

**Comment by cmungall** [comment]
works as expected!

**Comment by julesjacobsen** [comment]
Thanks @kshefchek! @ksewalk @camenden @knoddin is this OK?

**Comment by knoddin** [comment]
Yes, works well. Thanks, @kshefchek!
