### ISSUE TITLE
Top-level system terms for question starting points

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/phenotypr#3]
@kshefchek, sorry here's another one for you. Perhaps @mellybelly and @jmcmurry could assist too?

We need to define the starting point top-level laypersons terms for the questionnaire to work through.

e.g. Limbs, Head, Trunk (just made these up off the top of my head, so they are probably wrong)

**Comment by pnrobinson** [comment]
I have started to define top level categories for display on the HPO webpage and on the HPO Workbench. Could we please standardize on one solution for all of Monarch? The classes I have made can in theory also do multiple levels, although for right now I am just showing things like "Cardiology". I made up the names of the categories, but I think that they will be recognizable by lay people too. 
One way to standardize would be to make an ini file and store it say in the obo phenotype repository.

**Comment by kshefchek** [comment]
We could use all direct subclasses as phenotypic abnormality as a starting point until it is formalized, http://compbio.charite.de/hpoweb/showterm?id=HP:0000118

**Comment by cmungall** [comment]
Make a subset and put in HPO
